
  CREATE TABLE "EMPLEADO" 
   (	"RELA_PERSONA" NUMBER(10,0) CONSTRAINT "NL_EMPLEADO_RELA_PERSONA" NOT NULL ENABLE, 
	"ID_EMPLEADO" NUMBER(10,0) NOT NULL ENABLE, 
	"FECHAINGRESO" DATE, 
	"DEPARTAMENTO" NUMBER(2,0), 
	"CATEGORIA" NUMBER(2,0), 
	"ESTADO" NUMBER(2,0), 
	"SUELDOBRUTO" NUMBER(10,2), 
	 CONSTRAINT "PK_EMPLEADO" PRIMARY KEY ("ID_EMPLEADO"), 
	 CONSTRAINT "FK_EMPLEADO_PERSONA" FOREIGN KEY ("RELA_PERSONA")
	  REFERENCES "PERSONA" ("ID_PERSONA") ENABLE
   ) ;
CREATE SEQUENCE  "S_EMPLEADO"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

  CREATE OR REPLACE TRIGGER "PK_EMPLEADO" 
   before insert on "EMPLEADO" 
   for each row 
begin  
  select S_EMPLEADO.nextval into :NEW."ID_EMPLEADO" from dual; 
end;
/
ALTER TRIGGER "PK_EMPLEADO" ENABLE;